### ISSUE TITLE
Missing MATLAB function?

### ISSUE THREAD

**Issue by BarbJel** [yamsissamy/PlantPhys2017#1]
Hello,

I wanted to use your pipeline for my data but run into a problem. I followed the instructions and when I got to the MATLAB part it is not working (error: unable to resolve the name 'InputFiji.m'.) The PersisPlusShape.m which I should've put into single folder with the rest of the functions is not attached here and I am unable to find it, I am brand new to MATLAB and have no idea if that is the actual problem. Do you have any idea what could have gone wrong? Could you maybe provide me with the missing function?

Thank you so much in advance.
Barbora Jelínková

**Comment by yamsissamy** [comment]
Hello Barbora, I apologize for the late reply. 
I ran into several problems with matlab and have since moved to other languanges. 
Please contact me at sbelteto@nmsu.edu explaining the analysis you want to do and I'll try help as much as I can.
